// flow-typed signature: ee287000dd603168c0bbe5df50c8b566
// flow-typed version: <<STUB>>/eslint-watch_v^3.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-watch/src/arg-parser' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/cli' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/eslint/cli' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/eslint/help' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/executor' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/formatters/helpers/characters' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/formatters/helpers/error-warning' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/formatters/helpers/success' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/formatters/simple-detail' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/formatters/simple-success' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/formatters/simple' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/log' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/options' {
  declare module.exports: any;
}

declare module 'eslint-watch/src/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-watch/src/arg-parser.js' {
  declare module.exports: $Exports<'eslint-watch/src/arg-parser'>;
}
declare module 'eslint-watch/src/cli.js' {
  declare module.exports: $Exports<'eslint-watch/src/cli'>;
}
declare module 'eslint-watch/src/eslint/cli.js' {
  declare module.exports: $Exports<'eslint-watch/src/eslint/cli'>;
}
declare module 'eslint-watch/src/eslint/help.js' {
  declare module.exports: $Exports<'eslint-watch/src/eslint/help'>;
}
declare module 'eslint-watch/src/executor.js' {
  declare module.exports: $Exports<'eslint-watch/src/executor'>;
}
declare module 'eslint-watch/src/formatters/helpers/characters.js' {
  declare module.exports: $Exports<'eslint-watch/src/formatters/helpers/characters'>;
}
declare module 'eslint-watch/src/formatters/helpers/error-warning.js' {
  declare module.exports: $Exports<'eslint-watch/src/formatters/helpers/error-warning'>;
}
declare module 'eslint-watch/src/formatters/helpers/success.js' {
  declare module.exports: $Exports<'eslint-watch/src/formatters/helpers/success'>;
}
declare module 'eslint-watch/src/formatters/simple-detail.js' {
  declare module.exports: $Exports<'eslint-watch/src/formatters/simple-detail'>;
}
declare module 'eslint-watch/src/formatters/simple-success.js' {
  declare module.exports: $Exports<'eslint-watch/src/formatters/simple-success'>;
}
declare module 'eslint-watch/src/formatters/simple.js' {
  declare module.exports: $Exports<'eslint-watch/src/formatters/simple'>;
}
declare module 'eslint-watch/src/log.js' {
  declare module.exports: $Exports<'eslint-watch/src/log'>;
}
declare module 'eslint-watch/src/options.js' {
  declare module.exports: $Exports<'eslint-watch/src/options'>;
}
declare module 'eslint-watch/src/watcher.js' {
  declare module.exports: $Exports<'eslint-watch/src/watcher'>;
}
