// flow-typed signature: 91ffd2e14b6dbe396a43b476d67c5ca2
// flow-typed version: <<STUB>>/lodash.mapvalues_v^4.6.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.mapvalues'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.mapvalues' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.mapvalues/index' {
  declare module.exports: $Exports<'lodash.mapvalues'>;
}
declare module 'lodash.mapvalues/index.js' {
  declare module.exports: $Exports<'lodash.mapvalues'>;
}
