// flow-typed signature: 168bf6ce7db26e94d4f9b4e39abda09f
// flow-typed version: <<STUB>>/mindfront-redux-utils_v^1.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mindfront-redux-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mindfront-redux-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mindfront-redux-utils/lib/addMeta' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/composeMiddleware' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/composeReducers' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/createMiddleware' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/createPluggableMiddleware' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/createReducer' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/index' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/prefixActionCreator' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/lib/prefixReducer' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/addMeta' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/composeMiddleware' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/composeReducers' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/createMiddleware' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/createPluggableMiddleware' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/createReducer' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/index' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/prefixActionCreator' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils/src/prefixReducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mindfront-redux-utils/lib/addMeta.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/addMeta'>;
}
declare module 'mindfront-redux-utils/lib/composeMiddleware.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/composeMiddleware'>;
}
declare module 'mindfront-redux-utils/lib/composeReducers.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/composeReducers'>;
}
declare module 'mindfront-redux-utils/lib/createMiddleware.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/createMiddleware'>;
}
declare module 'mindfront-redux-utils/lib/createPluggableMiddleware.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/createPluggableMiddleware'>;
}
declare module 'mindfront-redux-utils/lib/createReducer.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/createReducer'>;
}
declare module 'mindfront-redux-utils/lib/index.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/index'>;
}
declare module 'mindfront-redux-utils/lib/prefixActionCreator.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/prefixActionCreator'>;
}
declare module 'mindfront-redux-utils/lib/prefixReducer.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/lib/prefixReducer'>;
}
declare module 'mindfront-redux-utils/src/addMeta.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/addMeta'>;
}
declare module 'mindfront-redux-utils/src/composeMiddleware.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/composeMiddleware'>;
}
declare module 'mindfront-redux-utils/src/composeReducers.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/composeReducers'>;
}
declare module 'mindfront-redux-utils/src/createMiddleware.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/createMiddleware'>;
}
declare module 'mindfront-redux-utils/src/createPluggableMiddleware.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/createPluggableMiddleware'>;
}
declare module 'mindfront-redux-utils/src/createReducer.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/createReducer'>;
}
declare module 'mindfront-redux-utils/src/index.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/index'>;
}
declare module 'mindfront-redux-utils/src/prefixActionCreator.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/prefixActionCreator'>;
}
declare module 'mindfront-redux-utils/src/prefixReducer.js' {
  declare module.exports: $Exports<'mindfront-redux-utils/src/prefixReducer'>;
}
