// flow-typed signature: d291ed53e3bdc41de7633d47ba44df00
// flow-typed version: <<STUB>>/@jedwards1211/eslint-config_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jedwards1211/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jedwards1211/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@jedwards1211/eslint-config/index' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config'>;
}
declare module '@jedwards1211/eslint-config/index.js' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config'>;
}
